### ISSUE TITLE
Is Radiance ready for production?

### ISSUE THREAD

**Issue by allchemist** [Shirakumo/radiance#13]
Hi!

I'm wondering, how ready is this project for production usage? I'm developing a web-service (quite common, nothing unusual). Now i'm using caveman2 (http://8arrow.org/caveman/), but it seems quite non-stable.

Also, do you interested in recieving bug reports, if any?

Thanks, Ivan

**Comment by Shinmera** [comment]
I'm using it myself for a publicly facing website. However, you're going to need to qualify what you understand by "production ready" in order for me to really answer your question.

Bug reports are always welcome, of course.

**Comment by allchemist** [comment]
> However, you're going to need to qualify what you understand by "production ready"
I mean more-or-less stable api (meaning there will be no need in future to re-write with a new api), and no unexpected bugs. No need of highload in any way.

**Comment by Shinmera** [comment]
I currently have no plans or needs to change any part of the API, so it should be stable for a good long time. If anything the API is getting more stable as we're adding tests to the system.

If eventual need for changes does come along, I'll definitely take care to make it backwards compatible, or in the very least make upgrading trivial.

**Comment by allchemist** [comment]
Thanks.

Also, is there any example of any web site code? i'd love to have a code skeleton to start with

**Comment by Shinmera** [comment]
There's a tutorial and a bunch of existing applications linked on the [homepage](https://shirakumo.github.io/radiance-homepage/).

**Comment by allchemist** [comment]
Thanks, i'll definitely have a try of this project
