### ISSUE TITLE
Odd issue when updating

### ISSUE THREAD

**Issue by Davidbhodge** [Shirakumo/radiance#21]
Hi Nicolas,

This is more fyi than anything else 

I have been exploring radiance as you know and quite obviously I had inadvertantly changed some source which introduced an error. Silly me for leaving a window open. Rather than hunt down the change  I decided to update the dist and it pulled in your latest changes.

I blew away all the fasls before recompiling .

On the first attempt at loading I received this below. Now I am sorry that I did not take a screenshot, but it was complaining about an already declared virtualized module

===========================
[package org.shirakumo.radiance.lib.modularize.user].
....; 
    ; compilation unit aborted
    ;   caught 2 fatal ERROR conditions
; Evaluation aborted on #<SB-INT:SIMPLE-PROGRAM-ERROR "~@<~/sb-impl:print-symbol-with-prefix/ ~
                           already names an ordinary function or a ~
                           macro.~@:>" {1002525863}>.

=============================

I selected the continue restart (3 times) and the loading proceeded, but had not really compiled everything.  (eg (radiance:startup) was not defined. When I did another quickload of radiance, it worked!
Clearly there is something in my environment that was screwing things up, but I am at a loss to say what. If I can get it to reproduce the error I will post it, but as it is behaving normally now, it seems environmental  and may be hard to reproduce . Any thoughts you might have on where to look would be appreciated.

**Comment by Shinmera** [comment]
Without the stack traces that appeared during compilation I can't say what was going on there, sorry. I haven't heard or seen any other reports like this either so this is the first I hear of a problem like this.

**Comment by Davidbhodge** [comment]
yep - if it happens again I will capture the backtrace.
