### ISSUE TITLE
Radiance doesn't qualify for the TFB

### ISSUE THREAD

**Issue by GertThiel** [Shirakumo/radiance#37]
I invested a whole night to get Radiance running in Docker in a manner the TFB requires: The final container must answer requests almost immediately.

My multi stage build runs both the `radiance-bootstrap.lisp` and `start.lisp` in the build step container/image and copies all files into the final "production" container/image.

But still, after all the effort, `start.lisp` just reinstalls `postmodern` at every start.

I'm exhausted.

Can't you just support building standalone apps?

PS: Automating `radiance-bootstrap.lisp` and `start.lisp` is _extremely_ fragile.

**Comment by hjudt** [comment]
Check [container-lisp/s2i-lisp](https://github.com/container-lisp/s2i-lisp). It compiles everything and my radiance container starts up within 2 seconds.

**Comment by GertThiel** [comment]
Thanks, @hjudt.

Do you have a Dockerfile using that tool for a Radiance app by chance?

**Comment by hjudt** [comment]
You don't need a docker file, just the s2i tool. This produces a docker image. You might need a dockerfile if you have to install additional dependencies (e.g. c libraries) It's rather easy, just follow the instructions.
For an example, look at this: https://github.com/hjudt/sample-lisp-app
It might not be completely up-to-date but you can use it as a starting point. Note the .s2i subdir If you have any questions, please use the issues on the s2i-lisp project page on github, not here.

**Comment by GertThiel** [comment]
I have tried for three days to get Radiance TFB-compliant.

My patience is exhausted.

Please don't get that wrong. Radiance is fine and to start into a REPL is a nice thing in real life. But TFB is a benchmark, that antonym of reality.
