### ISSUE TITLE
Server Sent Events and WebSockets

### ISSUE THREAD

**Issue by polymath-in** [Shirakumo/radiance#47]
I am new to CL, wanting to develop a web application. Does Radiance have Server Sent Events and WebSocket features incorporated? Could you redirect me to appropriate tutorial-page on Radiance. I couldn't find myself.

If not, is there a plan to implement/incorporate SSE and WS features? With SSE, I guess I could use deeds package (by yourself) for message redirection/pub-sub? Thanks.

**Comment by Shinmera** [comment]
Both sse and ws are features of the backend server implementation. While it is conceivable that an interface could be added to smooth over the differences of those features between the various server implementations, this does not currently exist. However, if you simply settle for a specific server implementation that does offer those features, there's nothing stopping you from using them in conjunction with the rest of Radiance.
