### ISSUE TITLE
define-page uri is supposed to start with slash apparently, but contribs don't

### ISSUE THREAD

**Issue by sirherrbatka** [Shirakumo/radiance#52]
I am trying to build a simple application currently, and I noticed that I can't seem to get simple-auth working. http://localhost:8080/auth/register would simply show me the radiance page. After changing URI of the register page from "auth/register" to "/auth/register" it started working. Do I miss something?

**Comment by Shinmera** [comment]
Yes. Your change is incorrect. Every module is siloed to its own subdomain. As such, the page must live on the `auth` domain, and the `/register` path. If you want to access it, you need to either access the subdomain directly, or set up a route to translate the URI according to what you want.

There's a default translation route set up so you can access it from restricted domains like `localhost` by using `/!/domain/path` as in `localhost:8080/!/auth/register`.

Please read the lengthy tutorial linked from the documentation, as it goes over this.

**Comment by sirherrbatka** [comment]
Oh, sorry to bother you. I was using radiance back in 2015 and I forgot how it works since then.

**Comment by Shinmera** [comment]
That's alright, sorry if I came across as rash!

**Comment by sirherrbatka** [comment]
Nah. It is my own fault.
