### ISSUE TITLE
Welcome page can't be removed after i startup radiance for many times?

### ISSUE THREAD

**Issue by faywong** [Shirakumo/radiance#54]
I follow https://shirakumo.github.io/radiance/ to get the radiance up.
But whatever path i access(such as /auth/login), i will always see the welcome page given by r-welcome module.
How can i removed the welcome page and make the api path worked as expected.

condition: i have installed all the radiance-contribs in my local-projects.

**Comment by Shinmera** [comment]
The login page is *not* on the path `/auth/login`, but rather on the subdomain `auth` and the path `/login`. Either set up a route to redirect `/auth/login` to `auth./login`, or use the standard redirect route `/!/auth/login`. This is explained in the lengthy tutorial linked from the main documentation pages.

**Comment by faywong** [comment]
Ok, i figure it out exactly. also i noticed that the module/ASDF package need to be loaded explicitly before it take effects through

```lisp
(ql:quickload :r-simple-auth)
```
so 
```lisp
(radiance:list-modules)
```
is the available modules, and  they need to be loaded explicitly before works.
Sorry for i am new to common lisp.
