### ISSUE TITLE
Cant add your dist to quicklisp.

### ISSUE THREAD

**Issue by Filipp-Druan** [Shirakumo/radiance#59]
Hello!
I tried to add your dist in quicklisp:
`(ql-dist:install-dist "http://dist.tymoon.eu/shirakumo.txt")`
I had an error:
`Too many redirects (10) for #<URL "http://dist.tymoon.eu/shirakumo.txt">`
How I can fix this error?

**Comment by Filipp-Druan** [comment]
Thanks!

**Comment by ispringle** [comment]
> Use http://dist.shirakumo.org/shirakumo.txt for now. I have no idea why quicklisp fails with the redirects.

Could be wrong here, but I believe the issue is that the tymoon link is upgrading to HTTPS and ql doesn't support https.
