### ISSUE TITLE
Dependency to documentation-utils

### ISSUE THREAD

**Issue by mcheema** [Shirakumo/radiance#8]
As far as I can tell a dependency documentation-utils is not in quicklisp so I needed to git clone it to local-systems to allow radiance to load. Not a problem for me but just a heads up.

**Comment by Shinmera** [comment]
[It is, though.](https://github.com/quicklisp/quicklisp-projects/commit/9234d302826f53837ef7f9887b501d9536168234)

**Comment by mcheema** [comment]
strange I'll have to see why it didn't work for me. I'll delete the issue.
